services:
  webapi:
    image: webapi_product
    container_name: webapi_product
    build:
        context: .
        dockerfile: ./Product/docker/Dockerfile
    networks:
      - webapp-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    container_name: gateway
    build:
      context: .
      dockerfile: ./Gateway/docker/Dockerfile
    environment:
      - GOOGLECLIENTID=${GOOGLECLIENTID}
      - GOOGLECLIENTSECRET=${GOOGLECLIENTSECRET}
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - webapi
    networks:
      - webapp-network
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - webapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 1s
      timeout: 5s
      retries: 10
networks:
  webapp-network:
    driver: bridge
