scrape_configs:
  - job_name: 'docker'
    docker_sd_configs:
      - host: "tcp://host.docker.internal:2375"
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: "container"