#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES__PRODUCT__USER WITH PASSWORD '$POSTGRES__PRODUCT__PASSWORD';
    CREATE DATABASE $POSTGRES__PRODUCT__DB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES__PRODUCT__DB TO $POSTGRES__PRODUCT__USER;
    ALTER DATABASE $POSTGRES__PRODUCT__DB OWNER TO $POSTGRES__PRODUCT__USER;

    CREATE USER $POSTGRES__INVENTORYSERVICE__USER WITH PASSWORD '$POSTGRES__INVENTORYSERVICE__PASSWORD';
    CREATE DATABASE $POSTGRES__INVENTORYSERVICE__DB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES__INVENTORYSERVICE__DB TO $POSTGRES__INVENTORYSERVICE__USER;
    ALTER DATABASE $POSTGRES__INVENTORYSERVICE__DB OWNER TO $POSTGRES__INVENTORYSERVICE__USER;

    CREATE USER $POSTGRES__ORDERSERVICE__USER WITH PASSWORD '$POSTGRES__ORDERSERVICE__PASSWORD';
    CREATE DATABASE $POSTGRES__ORDERSERVICE__DB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES__ORDERSERVICE__DB TO $POSTGRES__ORDERSERVICE__USER;
    ALTER DATABASE $POSTGRES__ORDERSERVICE__DB OWNER TO $POSTGRES__ORDERSERVICE__USER;

    CREATE USER $POSTGRES_AUTH_USER WITH PASSWORD '$POSTGRES_AUTH_PASSWORD';
    CREATE DATABASE $POSTGRES_AUTH_DB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_AUTH_DB TO $POSTGRES_AUTH_USER;
    ALTER DATABASE $POSTGRES_AUTH_DB OWNER TO $POSTGRES_AUTH_USER;
EOSQL

