name: Publish Products.Common to GitHub Packages

on:
  push:
    paths:
      - 'Common/Products.Common/**'
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
          source-url: https://nuget.pkg.github.com/mak27arr/index.json

      - name: Restore dependencies
        run: dotnet restore Common/Products.Common/Products.Common.csproj

      - name: Build the project
        run: dotnet build Common/Products.Common/Products.Common.csproj --configuration Release

      - name: Generate version from last tag
        id: version
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV || echo "VERSION=1.0.0" >> $GITHUB_ENV

      - name: Pack the project (Create NuGet package)
        run: dotnet pack Common/Products.Common/Products.Common.csproj --configuration Release --output ./nupkgs --version-suffix "${{ env.VERSION }}"

      - name: Push package to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
