name: Build and Publish Products.Common

on:
  push:
    paths:
      - 'Common/Products.Common/**'
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore Common/Products.Common/Products.Common.csproj

      - name: Build the project
        run: dotnet build Common/Products.Common/Products.Common.csproj --configuration Release

      - name: Pack the project (Create NuGet package)
        run: dotnet pack Common/Products.Common/Products.Common.csproj --configuration Release --output ./nupkgs

      - name: Get latest Git tag
        id: get_tag
        run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: ./nupkgs/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
